name:                ethambda
version:             0.1.0.0
github:              "githubuser/ethambda"
license:             BSD3
author:              "Frederik Hanghøj Iversen"
copyright:           "2018 Frederik Hanghøj Iversen"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:
  Please see the README on GitHub at <https://github.com/fredefox/ethambda#readme>

dependencies:
- base >= 4.7 && < 5
- mtl

library:
  source-dirs: src

executables:
  ethambda:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ethambda

tests:
  tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ethambda
